service: vamsi-tallam-apis

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  region: ap-south-1
  environment:
    NODE_PATH: "./:opt/node_modules"
  profile: ${opt:profile, 'default'}
  logs:
    restApi: true

functions:
  hello:
    handler: apis/handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
  unicorns:
    handler: apis/unicorns.unicornsList
    events:
      - http:
          path: /unicorns
          method: get
          cors: true
  visualTest:
    handler: apis/visualTest/index.visualTestDifference
    events:
      - http:
          path: /visual
          method: get
          cors: true
plugins:
  - serverless-offline

package:
  exclude:
    - nodejs/**
    - venv/**
